language: java

jdk:
  - oraclejdk8
services:
  - mysql
before_script:
  - mysql -e 'DROP DATABASE IF EXISTS bd_sistema'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bd_sistema;'
  - mysql -u root --default-character-set=utf8 bd_sistema < backend/bd/BD_VOLUNTARIADO_1.8.sql
